version: '3.8'

services:

    server:
        image: 'nginx:stable-alpine'
        build:
            context: .
            dockerfile: dockerfiles/nginx.dockerfile
        ports:
            - 8000:80
        depends_on:
            - php
            - mysql
        volumes:
            - ./src:/var/www/html
            - ./nginx/nginx.conf:/default.conf:ro
    php:
        build:
            context: .
            dockerfile: dockerfiles/php.dockerfile
        volumes:
            - ./src:/var/www/html:delegated

    mysql:
        image: mysql:8
        env_file:
            - ./env/mysql.env

    composer:
        build:
            context: ./dockerfiles
            dockerfile: composer.dockerfile
        volumes:
            - ./src:/var/www/html
    artisan:
        build:
            context: ./dockerfiles
            dockerfile: php.dockerfile
        entrypoint: ["php", "/var/www/html/artisan"]
        volumes:
            - ./src:/var/www/html

    npm:
        image: node:19-bullseye
        working_dir: /var/www/html
        entrypoint: ["npm"]
        volumes:
            - ./src:/var/www/html
